### ISSUE TITLE
Config file too complicated for simple use cases

### ISSUE THREAD

**Issue by wentasah** [CTU-IIG/demos-sched#13]
When one wants to run a simple scenarios, e.g., when writing a test suite, the configuration file syntax is too verbose. We should be more "intelligent" and apply reasonable defaults when certain information is missing from the config file.

- [x] **Missing slice definition**. We should create a slice for all CPUs
  and use sc_partition and be_partition from window. For example:

```yaml
windows:
  - length: 500
    sc_partition: SC1
    be_partition: BE1

```
should be the same as (on an 8-core system):
```yaml
windows:
  - length: 500
    slices:
      - cpu: 0-7
        sc_partition: SC1
        be_partition: BE1
```

- [x] **Partition definition in window**. In many cases, partition will be
  executed in just one window. In such a case, we should not require
  creating the partition outside of the window. For example:

```yaml
windows:
  - length: 500
    sc_processes:
      - cmd: proc1
      	budget: 500
```
should be the same as
```yaml
windows:
  - length: 500
    sc_partition: SC1
partitions:
  - name: SC1
    processes:
      - cmd: proc1
        budget: 500
```

- [x] **Default budget**. When defining the parition inside a window (as
  above) and the budget is missing, it should default to 60% of window
  length for SC processes and 100% for BE processes.
  
```yaml
windows:
  - length: 500
    sc_processes:
      - cmd: proc1
```

- [x] **Process as string**. When the processes is not a string or
      array of strings, we should treat is as `cmd`s without budget.
      For example:
	  
```yaml
windows:
  - length: 500
    sc_processes: "proc1"
```
should be the same as
```yaml
windows:
  - length: 500
    sc_processes:
      - cmd: proc1
```

Similarly:

```yaml
windows:
  - length: 500
    sc_processes: [ "proc1", "proc2"]
      - cmd: proc1
      	budget: 500
```
should be the same as
```yaml
windows:
  - length: 500
    sc_processes:
      - cmd: proc1
      - cmd: proc2
```
