### ISSUE TITLE
DEmOS fails when switching processes.

### ISSUE THREAD

**Issue by benedond** [CTU-IIG/demos-sched#65]
DEmOS fails with the following error:
```
>>> 14:18:04.699 [critical] Assertion failed: `running_process == nullptr`
>>> 14:18:04.699 [critical]     at ../src/slice.cpp:39 (bool Slice::load_next_process(time_point))
>>> 14:18:04.699 [critical] Unwinding stack and exiting...
>>> 14:18:04.700 [error] rmdir /sys/fs/cgroup/freezer//demos/be_a53/proc0: Device or resource busy
...
```
when executing this configuration:
```
# Run this as "demos-sched -p imx8_per_process -c demos-cfg1.yaml"
partitions:
  - name: be_a53
    processes:
      - {budget: 60000, frequency: 1200, cmd: "cd /root/thermobench/build/benchmarks/autobench_2.0/single; ./matrix-4M -v0 -c4 -i999999999"}                                                                      
      - {budget: 60000, frequency: 1104, cmd: "cd /root/thermobench/build/benchmarks/autobench_2.0/single; ./matrix-4M -v0 -c4 -i999999999"}                                                                      
      - {budget: 60000, frequency:  896, cmd: "cd /root/thermobench/build/benchmarks/autobench_2.0/single; ./matrix-4M -v0 -c4 -i999999999"}                                                                      
      - {budget: 60000, frequency:  600, cmd: "cd /root/thermobench/build/benchmarks/autobench_2.0/single; ./matrix-4M -v0 -c4 -i999999999"}                                                                      
      - {budget: 60000, frequency:  600, cmd: "sleep inf"}
  - name: be_a72
    processes:
      - {budget: 60000, frequency: 1596, cmd: "cd /root/thermobench/build/benchmarks/autobench_2.0/single; ./matrix-4M -v0 -c2 -i999999999"}                                                                      
      - {budget: 60000, frequency: 1296, cmd: "cd /root/thermobench/build/benchmarks/autobench_2.0/single; ./matrix-4M -v0 -c2 -i999999999"}                                                                      
      - {budget: 60000, frequency: 1056, cmd: "cd /root/thermobench/build/benchmarks/autobench_2.0/single; ./matrix-4M -v0 -c2 -i999999999"}                                                                      
      - {budget: 60000, frequency:  600, cmd: "cd /root/thermobench/build/benchmarks/autobench_2.0/single; ./matrix-4M -v0 -c2 -i999999999"}                                                                      
      - {budget: 60000, frequency:  600, cmd: "sleep inf"}
windows:
  - length: 1000
    slices:
      - cpu: 0-3
        be_partition: be_a53
      - cpu: 4-5
        be_partition: be_a72
```

The error seems to occur after 60 seconds of the execution (after the first process is finished).
