### ISSUE TITLE
Process never executed

### ISSUE THREAD

**Issue by wentasah** [CTU-IIG/demos-sched#67]
When running demos as `demos-sched -c config.yaml`, where `config.yaml` contains:
```yaml
partitions:
  - name: SC1
    processes:
      - cmd: yes > /dev/null
        budget: 1500
  - name: SC2
    processes:
      - cmd: yes > /dev/null
        budget: 1500
  - name: SC3
    processes:
      - cmd: yes > /dev/null
        budget: 1500
windows:
  - length: 1500
    slices:
      - cpu: 0
        sc_partition: SC1
      - cpu: 4
        be_partition: SC2
      - cpu: 5
        be_partition: SC3

```
only the process on CPU0 gets executed. When changing the budgets to 500, it seems that SC2 and SC3 run only after SC1 finishes. I think all processes should run simultaneously. @MatejKafka, can you look at it?
